export const provinciasConCiudades = {
  "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil"],
  "CABA": ["Ciudad Autónoma de Buenos Aires"],
  "Córdoba": ["Córdoba", "Villa María", "Río Cuarto", "Carlos Paz"],
  "Santa Fe": ["Rosario", "Santa Fe", "Rafaela", "Venado Tuerto"],
  "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Luján de Cuyo"],
  "Tucumán": ["San Miguel de Tucumán", "Tafí Viejo", "Yerba Buena"],
  "Salta": ["Salta", "Orán", "Tartagal"],
  "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú"],
  "Misiones": ["Posadas", "Oberá", "Eldorado"],
  "Chaco": ["Resistencia", "Sáenz Peña"],
  "Corrientes": ["Corrientes", "Goya"],
  "San Juan": ["San Juan", "Rawson"],
  "San Luis": ["San Luis", "Villa Mercedes"],
  "Neuquén": ["Neuquén", "Plottier"],
  "Río Negro": ["General Roca", "Bariloche", "Viedma"],
  "Chubut": ["Comodoro Rivadavia", "Trelew", "Puerto Madryn"],
  "La Pampa": ["Santa Rosa", "General Pico"],
  "Catamarca": ["San Fernando del Valle", "Andalgalá"],
  "La Rioja": ["La Rioja"],
  "Formosa": ["Formosa"],
  "Jujuy": ["San Salvador de Jujuy", "Palpalá"],
  "Santa Cruz": ["Río Gallegos", "Caleta Olivia"],
  "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
};